items_db_path : data/kb/redial_db
train_path : data/processed/redial/train_wrl 
test_path : data/processed/redial/test_wrl

batch_size : 1
num_epochs : 10

num_samples_recall_train : 150
num_samples_rerank_train : 60
validation_recall_size : 500

temperature : 1.2

# For balancing the importance of Loss Functions
language_loss_train_coeff : 0.5
recall_loss_train_coeff : 0.3
rerank_loss_train_coeff : 1.0

# For Class Imbalance
num_pos_classes_dev: 38453
num_neg_classes_dev: 63076

output_file_path: "out/redial_train.txt"