items_db_path : data/kb/durecdial2_db
train_path : data/processed/durecdial2/durecdial2_all_train_placeholder_updated
test_path : data/processed/durecdial2/durecdial2_all_dev_placeholder_updated

batch_size : 1
epochs : 10

num_samples_recall_train : 500
num_samples_rerank_train : 60
validation_recall_size : 500

temperature : 1.2

# For balancing the importance of Loss Functions
language_loss_train_coeff : 0.5
recall_loss_train_coeff : 0.3
rerank_loss_train_coeff : 1.0

# For Class Imbalance
num_pos_classes_dev: 530
num_neg_classes_dev: 5777

output_file_path: "out/durec_train.txt"

# Load from ckpt
load_ckpt: False
ckpt_loc: runs/new_model_rec.pt

# Freeze specific parts of the model
freeze_2: False